version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - "D:/Projects/temp/untitled/frontend:/app"
    environment:
      - WATCHPACK_POLLING=true
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - "D:/Projects/temp/untitled/frontend:/app"
    command: ["npm", "run", "test"]
    environment:
      - WATCHPACK_POLLING=true
